name: conan # you probably want to 'snapcraft register <name>'
version: '1.18.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: C/C++ package manager  # 79 char long summary
description: |
  C/C++ package manager.
# adopt-info: conan

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:  
  conan:
    command: opt/conan/conan
    plugs: 
      - home
      - network

parts:
  conan-binaries:
    plugin: nil
    override-build: |
      set -x
      DEB_URL=https://dl.bintray.com/conan/installers/conan-ubuntu-64_1_18_2.deb
      DEB=$(basename "${DEB_URL}")
      echo "Downloading ${DEB_URL}..."
      wget --quiet "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      echo "Unpacking ${DEB}..."
      dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB}" ${SNAPCRAFT_PART_INSTALL}
      rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB}" 2>/dev/null    
      apt autoremove --yes
    build-packages:
      - dpkg
      - wget      
    stage-packages:
      - build-essential
      - python2.7